name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      docker_username:
        description: "Docker Hub username"
        required: true
        type: string
      image_name:
        description: "Docker image name"
        required: true
        type: string
      tag:
        description: "Docker image tag"
        required: true
        type: string

    secrets:
      docker_token:
        required: true

    outputs:
      image_url:
        description: "Full Docker image URL"
        value: ${{ jobs.docker.outputs.image_url }}

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      image_url: ${{ steps.image-info.outputs.image_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker inputs
        run: |
          if [ -z "${{ inputs.docker_username }}" ]; then
            echo "docker_username input is missing"
            exit 1
          fi

          if [ -z "${{ secrets.docker_token }}" ]; then
            echo "docker_token secret is missing"
            exit 1
          fi

          echo "Docker inputs are available"

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/github-actions-capstone:latest .

      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/github-actions-capstone:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/github-actions-capstone:latest
