name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        description: "Docker image name"
        required: true
        type: string
      tag:
        description: "Docker image tag"
        required: true
        type: string

    secrets:
      docker_username:
        required: true
      docker_token:
        required: true

    outputs:
      image_url:
        description: "Full Docker image URL"
        value: ${{ jobs.docker.outputs.image_url }}

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      image_url: ${{ steps.image-info.outputs.image_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker secrets
        run: |
          if [ -z "${{ secrets.docker_username }}" ]; then
            echo "docker_username is missing"
            exit 1
          fi

          if [ -z "${{ secrets.docker_token }}" ]; then
            echo "docker_token is missing"
            exit 1
          fi

          echo "Docker secrets are available"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }} .
          docker push ${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Set image URL output
        id: image-info
        run: |
          echo "image_url=${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
